## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [16]:
import pandas as pd

In [17]:
df =pd.read_csv('fake_train.csv', sep=';')

In [18]:
df.head()

,Unnamed: 0,title,text,label
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0

In [19]:
df.shape

(24353, 4)

In [20]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [21]:
###Drop Nan Values
df=df.dropna()
## since this is a text data, we cannot replace the missing values with anything so we will drop

In [22]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [23]:
## Get the Dependent features
y=df['label']

In [24]:
X.shape

(24353, 3)

In [25]:
y.shape

(24353,)

In [26]:
import tensorflow as tf

In [27]:
tf.__version__

'2.20.0'

In [28]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [29]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [30]:
messages=X.copy()

In [31]:
messages['title'][1]

"China says Trump call with Taiwan president won't change island's status"

In [32]:
messages

,Unnamed: 0,title,text
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s..."
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...
...,...,...,...
24348,24348,Mexico Senate committee OK's air transport dea...,MEXICO CITY (Reuters) - A key committee in Mex...
24349,24349,BREAKING: HILLARY CLINTON’S STATE DEPARTMENT G...,IF SHE S NOT TOAST NOW THEN WE RE IN BIGGER TR...
24350,24350,trump breaks from stump speech to admire beaut...,kremlin nato was created for agression \nruss...
24351,24351,NFL PLAYER Delivers Courageous Message: Stop B...,Dallas Cowboys star wide receiver Dez Bryant t...
24352,24352,NORDSTROM STOCK TAKES NOSEDIVE After Trump Twe...,UPDATE: Nordstrom stock closed up slightly tod...

In [33]:
#messages.reset_index(inplace=True)

In [34]:
messages

,Unnamed: 0,title,text
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s..."
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...
...,...,...,...
24348,24348,Mexico Senate committee OK's air transport dea...,MEXICO CITY (Reuters) - A key committee in Mex...
24349,24349,BREAKING: HILLARY CLINTON’S STATE DEPARTMENT G...,IF SHE S NOT TOAST NOW THEN WE RE IN BIGGER TR...
24350,24350,trump breaks from stump speech to admire beaut...,kremlin nato was created for agression \nruss...
24351,24351,NFL PLAYER Delivers Courageous Message: Stop B...,Dallas Cowboys star wide receiver Dez Bryant t...
24352,24352,NORDSTROM STOCK TAKES NOSEDIVE After Trump Twe...,UPDATE: Nordstrom stock closed up slightly tod...

In [35]:
import nltk
import re
from nltk.corpus import stopwords

In [36]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [37]:
## Data preprocessing

In [38]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

corpus=[]
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
  review = review.lower()
  review= review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


#This is a list comprehension. It iterates through every word, removes stopwords using a condition, and applies Porter stemming to the remaining words.

In [39]:
corpus

['palestinian switch christma light bethlehem anti trump protest',
 'china say trump call taiwan presid chang island statu',
 'fail trump organ credit score make laugh',
 'zimbabw militari chief china trip normal visit beij say',
 'uncourag presid ever receiv courag award proce whine current presid',
 'suspect boko haram suicid bomber kill least nigeria offici',
 'watch john oliv present gop debat clowntown f ck world sh tshow',
 'senat democrat ask trump attorney gener pick recus russia probe',
 'trump humili republican latest hissi fit side democrat debt ceil',
 'maci get boot loyal custom fire trump',
 'north korea nuclear test pacif logic terrifi',
 'czech polic ask parliament allow prosecut prospect pm babi',
 'one democrat refus cast elector vote crook hillari could end video',
 'watch senat al franken rip ted cruz new one insult senat hear',
 'nearli half american still oppos republican tax bill reuter ipso poll',
 'white hous declin say trump made decis climat accord',
 'u appeal court hear argument virginia voter id law',
 'wow unhing clown democrat goe nut hous floor obamacar debat video',
 'heiress disney empir know gop scam us shred tax bill',
 'trump staffer admit boss idea daca',
 'argentina say satellit call detect like miss submarin',
 'trump gain ground clinton reuter ipso state nation',
 'carson hud agenc overse public hous feder mortgag program',
 'watch nanci pelosi come unglu call pie chart pie crust know differ billion dollar trillion dollar',
 'watch donald trump obsess desir use nuclear weapon',
 'biker trump travel futur ralli provid outsid secur paid soro thug hillari berni sander',
 'hill ariou must see iowa parad goer treat hillari prison float water balloon pass throw',
 'video burger king manag curs threaten custom ask refund',
 'god gay snl destroy religi freedom law hilari mock film promo video',
 'rememb trump biggest campaign promis yeah well kid',
 'mcconnel say discuss suprem court pick trump',
 'u plan move israel embassi sign failur iran leader say',
 'lol listen yoko ono primal respons trump win',
 'watch shock number swedish citizen walk girl rape middl eastern man car video',
 'obama plan expos immigr tennesse anxiou citizenship vote',
 'comment geniu child arrest interrog thrown juvi hero cop make homemad clock brian hodg',
 'power texa republican see tough road bathroom bill',
 'senat republican leader say plan vote compromis gun bill',
 'georg w bush ethic lawyer file complaint fbi director jame comey',
 'uk johnson russia ignor elect meddl',
 'south african court rule deliv setback zuma alli',
 'trump conclud fed chair interview could decid next week sourc',
 'prime minist trudeau say canada abandon nafta talk',
 'hurrican irma worsen latin america fuel suppli crunch',
 'queen declar rnc use music unauthor',
 'highlight trump presid januari pm est gmt',
 'one disgrac photo captur essenc hillari clinton entir campaign',
 'next year ugli k',
 'washington post prais michel obama reclaim imag openli support racist cop hate black live matter',
 'budapest closer moscow orban grant money russian orthodox church',
 'afghan pakistan border villag brace berlin wall style divid',
 'wow white liber suggest black stupid get idscant figur use internet video',
 'china futur action could warrant forex manipul label treasuri nomine',
 'least six die colombia protest coca crop remov',
 'republican tax plan would let church enter polit fray',
 'secret servic arrest johnni depp trump assassin comment court doc show manag say abus wife',
 'simpson react trump elect predict happi video',
 'ivanka trump share famou jewish quot hilari credit harri potter star imag',
 'attack trump mitt romney awok sleep giant',
 'watch new clinton ad brilliantli goe trump product made usa',
 'u bomb drop afghanistan highest sinc new trump strategi',
 'u n plead end yemen blockad untold thousand die',
 'lie major lie shape obama presid',
 'obama scotu pick nail worst domest terrorist u histori video',
 'trump stop prais coast guard harvey effort vicious attack media video',
 'senat democrat push new gun control measur',
 'high school v p warn student terrorist need fear domest white christian men easi access gun',
 'u rescind obama plan undocu parent',
 'obama legaci washington lie isi lie syria',
 'algeria futur uncertain macron unlik dwell past visit',
 'releas horrifi cell phone video insid lavoy finicum vehicl show realli happen',
 'white hous deep denial dumpster fire healthcar plan detail',
 'trump brag number peopl come inaugur realiz protest',
 'watch nanci pelosi say heartbroken death rep steve scalis still aliv hospit video',
 'open border advoc nanci pelosi give gibberish laden reason oppos border wall understand part countri video',
 'hous member sign letter back israel u n',
 'turkish troop kurdish milit clash near iraqi border kill armi',
 'gaff day va gov terrymcauliff blame mani gun shoot lose million american day gun violenc video',
 'czech babi gain possibl support bid minor govern',
 'factbox contend pick key job trump administr',
 'u vote advanc fcc chairman nomin',
 'u russia cyber unit without trump notifi congress bill say',
 'unbeliev trump disgust comment black voter',
 'trump prepar execut order reduc u role u n ny time',
 'massiv screw may cost trump nomin fault',
 'alabama top judg face ethic charg gay marriag order',
 'oop state dept turn thousand e mail swore exist',
 'trump prove incred ignor world detail',
 'lot peopl us suddenli identifi white',
 'china urg north korea go danger direct',
 'titl',
 'new york governor unveil south bronx highway rebuild plan',
 'liber billmah use n word live tv kathi griffin video',
 'hous republican leader see puerto rico bill juli',
 'break news susan rice admit unmask us person interview msnbc media alli andrea mitchel video',
 'aclu defend illeg sue doj ice arrest illeg alien teen gang play fight',
 'russia potent weapon hoard gold',
 'missouri state rep dumbest idea ever help unarm peopl state capitol imag',
 'uk pm may say brexit transit period last around two year',
 'saudi led forc admit strike yemen capit hit civilian',
 'revis u travel ban still curtail tourism u n tourism bodi say',
 'former obama aid call trump psychopath',
 'utah oldest paper demand trump drop race scath must read editori',
 'mexican presid say pay trump wall make hitler warn',
 'stun first ladi melania trump welcom isra prime minist netanyahu video',
 'year old man write must read letter rnc explain vote trump',
 'angela merkel husband take melania ivanka tour p ss trump',
 'u senat mccain win arizona republican nomin contest',
 'pastafarian fight georgia right wear coland licens photo probabl win',
 'declassifi us intel report use discredit trump huge embarrass evid compil obama reelect',
 'erdogan spokesman call syrian fli zone without delay',
 'senat confirm trump pick zink interior secretari',
 'watch nbc report call trump lie repeatedli live press confer',
 'factbox key polici austria conserv far right coalit',
 'least three dead indian passeng train derail northern india',
 'children serenad pope st birthday appeal kidnap nun',
 'clinton lead trump point reuter ipso poll',
 'dem congressman humili trump one gloriou tweet prove absolut stupid imag',
 'obama stammer like crazi tri slam trump video',
 'franc germani concern trump move limit refuge',
 'trump say look phase corpor tax cut',
 'ship traffic could resum tuesday port arthur texa u coast guard',
 'hillari found friend debat know say fli hillaryclintonfli',
 'austria social democrat urg facebook unmask peopl behind smear campaign',
 'nato chief downplay concern format joint european armi',
 'sander say parti leader may rethink win',
 'peru colombia vow stand mexico row trump',
 'factbox compar contrast trump tweet vs privat comment ceo',
 'trump immigr speech mexico visit fill lie deceit racism',
 'spook catalonia eu ralli behind madrid warili',
 'trump nomin quarl fed top bank regul',
 'trump complet destroy promis end corrupt wall street video',
 'paul ryan say confid tax reform pass axio',
 'internet savag trump promot fox news propaganda tweet',
 'watch megyn kelli own transphob texa lt governor bathroom law',
 'saudi arabia swap asset freedom held graft purg sourc',
 'refuge crisi influx boon german integr studi',
 'syrian govern deleg postpon departur geneva talk report',
 'syrian opposit reject russia sponsor peac initi',
 'creepi never believ derang thing trump fan cardboard donald daili video',
 'trump signal support alexand murray healthcar plan senat',
 'barack obama goe compar presid trump hitler front chicago audienc',
 'syndrom babi allow born fli babi might make peopl think decis',
 'karma dem rep knock stage fall sign republican receiv death threat video',
 'pelosi lose call tax cut end world armageddon video',
 'tim allen crack joke obama would destroy potu made joke video',
 'ted cruz bad lip read everyth never knew want video',
 'bill nye crush hole start rumor would debat sarah palin video',
 'trump speak qatar emir gulf uniti terror fight white hous',
 'lawyer shot kill wife blame black live matter video',
 'trump fbi comment russian aim cooper aid',
 'search rebound trump ramp attack clinton',
 'get readi civil unrest survey find american concern elect violenc',
 'hillari live tweet trump speech absolut point tweet',
 'china urg u bar taiwan deleg trump inaugur',
 'http fedup wpengin com wp content upload entitl jpg',
 'trump campaign cop black ralli goer longer welcom video',
 'two suicid attack iraq kirkuk kill least five',
 'dnc hack cold war fals flag',
 'u help restor water power raqqa fall islam state',
 'video mad street cop hurt baltimor obama plan chao spread',
 'nepal elect new parliament year instabl',
 'white hous say chang nsc trump differ',
 'georgia governor order evacu savannah coast ahead irma',
 'uganda presid boost militari unit rural support slip away',
 'report get bush cia director admit waterboard tortur use clever trick video',
 'classic unhing liber lose scream nooo soon trump sworn video',
 'say obama give go ahead new un region hub washington dc plan use center disturb',
 'florida governor goe obama second amend kill individu radic islam kill video',
 'syrian armi take full control deir al zor islam state observatori',
 'comment im law today nga cop fire use social media declar racism albert wesker',
 'franc move rais minimum food price limit promot',
 'wall close trump disgrac nation secur advis face indict team mueller',
 'kremlin cooper russia u north korea ria',
 'poet dock israel hunt lone wolf assail onlin',
 'cop drag half nake woman courtroom judg awesom video',
 'japan pm stress import tpp trade pact clinton meet',
 'dingbat maxin water tell islam societi republican tri prevent sharia law enforc america contrari american valu threaten nation secur video',
 'mcdonald delet trump tweet say twitter account compromis',
 'watch rabid trump support call liber genocid frighten arizona ralli',
 'report creepi donald trump hit today tweet',
 'professor head court threaten strike estacio layoff brazil',
 'sander block obama nomine lead fda cite industri tie',
 'court order nigeria pay million war victim',
 'eu mp threaten cambodia aid trade crackdown',
 'muslim migrant show appreci german host spread fece vomit blood asylum wall',
 'new czech govern seek confid vote januari pm',
 'clinton campaign collect dirt readi take donald trump',
 'muslim silent terror attack blame trump wit give descript tall hispan kill ny imam assist video',
 'prepar invad us deploy addit soldier syria iraq',
 'catalan leader say proceed oct independ referendum',
 'man kill arrow kenyan villag edg elect',
 'watch mattress compani imposs vile sale commerci video',
 'u unveil retir advic rule next week sourc',
 'trump warn vote flip machin',
 'schwarzenegg fire quit apprentic trump',
 'boom rep louie gohmert r tx rip obama gun grab legisl minion radic islam kill peopl video',
 'white hous say rollback obamacar must part short term fix',
 'key trump advisor elton john perform inaugur first american presid us histori enter white hous pro gay right stanc',
 'china state media attack western democraci ahead congress',
 'donald trump tweet direct threat berni sander support tweet',
 'ceasefir deal seal rebel pocket near damascu',
 'saudi arabia detain princ ex minist anti corrupt drive',
 'great speech donald trump get dig hillari say three word video',
 'day result wisconsin recount hillari gonna like',
 'u commerc secretari say market access protection top china issu',
 'reckless democrat parti creat russian scarecrow us media polit',
 'german elect chief urg action ensur vote softwar hack',
 'tea parti republican huelskamp lose elect bid u hous',
 'clinton campaign chairman testifi hous russia probe',
 'presid obama stun oil compani crush propos video',
 'break news trump admin announc massiv tax cut busi massiv tax reform video',
 'philippin russia sign two militari deal',
 'putin say russia respond kind u quit missil treati',
 'hilari trump expos stupid nbc puppet report video',
 'u japan agre china play larger role north korea',
 'fish boat capsiz south korea eight kill',
 'uk rais grave concern illeg settlement israel netanyahu may offic',
 'sever senior state depart offici leav post offici',
 'senat panel approv wray nomin fbi director',
 'pennsylvania capit ex mayor plead guilti theft case',
 'uk say briton kidnap nigeria last month kill three other releas',
 'let clear vote warmong hillari clinton vote world war',
 'uk brexit withdraw bill debat decemb',
 'comment reason diet suck import concept manospher taught',
 'u senat urg nhtsa acceler takata air bag recal',
 'greec give million compens flood victim',
 'u presid trump arriv israel flight riyadh',
 'syrian militia aim push islam state raqqa within month',
 'newt gingrich boost economi real danger speaker pelosi video',
 'salli yate bombshel trump warn flynn expos white hous blackmail video',
 'jail catalonia leader santi vila leav jail pay bail',
 'hungarian pm orban hail trump victori great news',
 'trevor noah dropkick donald trump truli brutal one liner video',
 'fox news report ask mayor use taxpay money sue famili epic christma light display video',
 'trump panic judg first day offic ridicul standard',
 'russia host summit could decis syria peac erdogan',
 'illinoi entir team yr old kid perform disgust act disrespect flag law enforc guidanc coach',
 'mobi liter laugh donald trump invit dj inaugur',
 'fl pastor accident shoot wife head clean gun',
 'break video dirti bomb fear nyc polic offic target place back obama deblasio wear nuclear bomb detector juli th weekend',
 'watch khizr khan destroy trump interview attack famili',
 'man walk target undercov camera watch manag shock repli ask use women bathroom',
 'republican vote defund u n retali one singl issu',
 'qatar emir say open trump host talk gulf crisi cb',
 'debt limit showdown loom sooner wealthi bet trump tax cut',
 'eric trump claim democrat even peopl fox news interview video',
 'transgend militari personnel sue trump servic ban',
 'senat republican blast donald trump racist danger muslim ban full forc',
 'irma updat latest look hurrican strengthen cat great danger florida key',
 'indian court privaci rule blow govern',
 'alabama offici certifi senat elect jone today despit challeng cnn',
 'democrat seek fbi probe alleg russia seek influenc u vote',
 'key u senat demand answer equifax hack',
 'boiler room ep charlottesvil histori violent cultur revolut',
 'bare quarter catalan want pursu split spain poll',
 'justic depart ask u judg reconsid rule trump sanctuari order',
 'sexual abus accus sue ex hous speaker hastert million',
 'trump get tire hamilton feud reignit attack new york time instead tweet',
 'treasuri chief say review iran aircraft licens',
 'trump inner circl reveal bizarr new goal light dwindl odd',
 'trump hold town hall meet busi leader',
 'russia deni bomb u back militia syria ria',
 'uk may signal foreign minist johnson could sack',
 'trump tri forc dem hand border wall fund fail bigli',
 'former alli nigeria buhari prepar contest presid',
 'key u senat say time right new north korea legisl',
 'former presidenti rival jeb bush say vote trump',
 'weil sie sich pr gelten gef ngnisdirektor erteilt h ftlingen lebenslang hausverbot',
 'eu leader seek greater reduct africa immigr',
 'u mull potenti f sale greec trump',
 'biden visit iraq show support amid multipl crise',
 'treasuri dept depict ladi liberti black woman new u coin',
 'u navi carrier drill japanes navi amid north korean tension',
 'factbox contend senior job trump administr',
 'life love enamel pin youll love etsi shop dont care enamel pin youll explod pictur bulldog puppi doesnt youll lose shit amazinglook pizza dont well find someth',
 'famili feud presid trump reportedli blame jare kushner mueller indict',
 'mexico say way pay trump wall',
 'idea less hope leav syria crisi back burner u n',
 'obama crook doj hide massiv hillari scandal u govern spent million dollar went world bankrupt destroy life protect hillari clinton crime',
 'result new post debat poll show major swing key demograph video',
 'momentum grow anoth grand coalit germani',
 'russia foreign minist discuss syria turkish counterpart',
 'seneg rebel issu warn astron miner sand mine',
 'law abid citizen carri gun groceri chain refus serv',
 'senat call panel investig russian hack',
 'trump agricultur advisor new nicknam clinton wors trump screenshot',
 'wapo trump plan go around senat replac session loyal stoog',
 'donald trump give epic respons pga move trump doral mexico',
 'presid obama call trump ask russia hack elect amaz',
 'black woman report white man choke son cop show attack video',
 'trump deleg indict weapon child pornographi charg',
 'break crook va governor close hillari friend gave wife fbi offici overse hillari email investig',
 'u see busi usual port entri travel ban start',
 'major american say clinton first debat trump reuter ipso poll',
 'activist troll republican phoni condol orlando shoot',
 'trump legal team directli contradict investig yet',
 'hungari prosecutor probe account opposit jobbik parti',
 'iowa kick u presidenti race caucu tradit',
 'whirlpool washer war balanc act trump',
 'ted cruz sorri cheat way iowa win video',
 'japanes girl say school forc dye hair black sue govern media',
 'petit file kenya court challeng kenyatta elect victori',
 'justic depart halt settlement fund outsid group',
 'suspect u drone target haqqani milit pakistan kill four',
 'pm may speak trump jerusalem say statu determin negoti',
 'studi show million non u citizen vote trump crazi think million illeg vote right',
 'australia queensland call snap elect test far right candid',
 'arizona republican say colleg kid make elect unfair unveil despic plan stop',
 'titl',
 'taylor swift besti leftist lie rape republican ruin wholesom imag',
 'trump lawyer make final suprem court pitch travel ban',
 'bannon take weapon breitbart smear quran kiss mcmaster scath hit piec',
 'conserv comment use nanci reagan death launch racist attack michel obama tweet',
 'bill reilli destroy donald trump rant shake fox news video',
 'trump fire open salvo riski test will beij',
 'poland refus accept muslim migrant may behind ec decis rule parti',
 'presid trump attend pari juli celebr',
 'racist trump support lose subway attack woman black video',
 'situat korean peninsula risk move hot phase ifax cite russian foreign minist',
 'good guy gun threaten shoot mcdonald drive thru worker video',
 'bigotri twitter eviscer mississippi gov anti gay law',
 'obama say trump comment women disqualifi',
 'white hous say focus get lowest possibl corpor tax rate',
 'suspect malta blogger murder sent trial',
 'turkey remain depend alli nato erdogan spokesman say',
 'china start formal legal proceed disgrac senior politician',
 'question presidenti candid spent campaign far answer may surpris',
 'putin shrug trump nuclear plan say democrat sore loser',

In [40]:
corpus[1]

'china say trump call taiwan presid chang island statu'

In [41]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[1856, 1146, 1633, 2574, 3894, 1287, 1391, 725],
 [891, 1632, 1391, 4274, 1692, 4081, 2631, 4187, 2235],
 [2503, 1391, 1877, 3312, 2708, 4922, 3255],
 [1889, 2577, 3259, 891, 2319, 2740, 972, 2422, 1632],
 [1533, 4081, 992, 2518, 3254, 1334, 3548, 2997, 1338, 4081],
 [314, 4197, 4863, 1098, 4967, 2090, 902, 1115, 1363],
 [4642, 4834, 1785, 878, 4114, 184, 3575, 3137, 2215, 4427, 2409, 1308],
 [3983, 2154, 977, 1391, 1162, 1144, 2899, 4579, 4300, 91],
 [1391, 2495, 3887, 1577, 3297, 4303, 3010, 2154, 1721, 3576],
 [283, 4897, 2, 4302, 1415, 4631, 1391],
 [3807, 3472, 2074, 2196, 793, 271, 2733],
 [2755, 4162, 977, 1000, 87, 1656, 37, 3018, 2621],
 [1326, 2154, 3640, 1661, 202, 385, 2343, 4844, 2036, 1777, 2920],
 [4642, 3983, 787, 4862, 1929, 3488, 4856, 945, 1326, 1240, 3983, 401],
 [2602, 4466, 1379, 345, 4957, 3887, 3790, 835, 1440, 3333, 527],
 [3601, 3632, 3381, 1632, 1391, 4397, 2420, 2794, 4315],
 [3742, 2051, 824, 401, 3555, 3027, 3954, 1940, 1097],
 [4741, 695, 3183, 2154, 1928, 1297, 3632, 4535, 69, 184, 2920],
 [3471, 3762, 3653, 57, 4114, 3048, 2954, 2300, 3790, 835],
 [1391, 288, 2894, 2780, 2634, 867],
 [2536, 1632, 2585, 4274, 1081, 2423, 1976, 2684],
 [1391, 1056, 2979, 2771, 1440, 3333, 2245, 280],
 [3465, 3645, 3440, 3333, 2809, 3632, 3188, 3909, 2656],
 [4642,
  768,
  3823,
  3498,
  4774,
  4274,
  3071,
  2688,
  3071,
  4446,
  57,
  1739,
  417,
  2682,
  4870,
  2682],
 [4642, 4952, 1391, 683, 2891, 3213, 2074, 102],
 [2074,
  1391,
  3277,
  2841,
  1711,
  2932,
  335,
  2480,
  1215,
  3014,
  840,
  4844,
  1131,
  1879],
 [4055,
  4214,
  1289,
  1883,
  2276,
  2807,
  797,
  1980,
  4844,
  3651,
  2985,
  2320,
  2733,
  2129,
  4607],
 [2920, 274, 2020, 3283, 3007, 2706, 1415, 977, 3068],
 [2214, 3351, 421, 507, 1076, 3442, 1097, 4607, 1964, 3665, 4816, 2920],
 [4451, 1391, 224, 2199, 3760, 4766, 3899, 3289],
 [4157, 1632, 4000, 3518, 824, 2899, 1391],
 [3742, 1363, 4075, 3630, 4264, 903, 89, 2405, 2472, 1632],
 [606, 4390, 166, 3006, 3658, 3979, 1391, 3880],
 [4642, 132, 3537, 2457, 1014, 3760, 4930, 3710, 2010, 4101, 1617, 2275, 2920],
 [2155, 1363, 3974, 3008, 290, 447, 3524, 385],
 [1672,
  1707,
  1668,
  1143,
  3760,
  2047,
  1283,
  4908,
  2180,
  4922,
  4704,
  254,
  88,
  556],
 [432, 3695, 3887, 1883, 2945, 3398, 4183, 835],
 [3983, 3887, 2472, 1632, 1363, 385, 2793, 362, 835],
 [4557, 2151, 687, 143, 3894, 1948, 4065, 2738, 2071, 614, 2109],
 [72, 3447, 4300, 3321, 3699, 2417],
 [2271, 633, 824, 1678, 2495, 967, 4631, 2026],
 [1391, 449, 1455, 1226, 2889, 2036, 434, 4417, 901, 972],
 [3113, 147, 3368, 1632, 3475, 3512, 4124, 4829],
 [3029, 1879, 1032, 320, 3523, 2270, 4033, 3468],
 [2031, 4428, 418, 3213, 1679, 2554],
 [445, 1391, 4081, 1228, 3018, 1573, 748],
 [1326, 4721, 2116, 3156, 1042, 4844, 2771, 772, 2199],
 [4417, 1018, 2420, 103],
 [2081,
  162,
  2834,
  4315,
  2155,
  2837,
  3945,
  237,
  3192,
  41,
  2180,
  379,
  4150,
  512,
  3936],
 [2320, 619, 2949, 1897, 582, 172, 22, 2741, 4759],
 [152, 2253, 773, 4331, 3348, 3328, 3445, 2244, 3652],
 [4741, 3601, 2301, 4955, 4150, 2203, 4897, 3888, 1008, 3213, 4383, 2920],
 [891, 2841, 3407, 2036, 2002, 195, 2700, 1718, 547, 1832],
 [902, 4932, 1813, 121, 725, 4967, 4091, 3216],
 [3887, 3790, 1363, 2386, 3285, 4759, 3973, 4191, 3200],
 [3259,
  1594,
  1143,
  2294,
  4117,
  1391,
  2021,
  1672,
  824,
  1626,
  1937,
  3283,
  1632,
  2433,
  780],
 [4714, 3346, 1391, 3699, 2123, 36, 2920],
 [1273, 1391, 765, 2031, 2304, 1325, 4607, 3312, 181, 1290, 4121, 3945],
 [1044, 1391, 832, 3134, 2692, 4158, 1148],
 [4642, 945, 2771, 3385, 2653, 1928, 1391, 624, 4397, 4044],
 [3742, 4740, 835, 2221, 953, 3697, 945, 1391, 1949],
 [3742, 2198, 2922, 1777, 4009, 3566, 1072, 4329, 1813],
 [2430, 1059, 2430, 3894, 2155, 4081],
 [2155, 2394, 2899, 538, 1623, 630, 25, 3742, 3071, 2920],
 [1391, 1084, 2834, 1379, 1399, 2041, 4993, 3885, 1044, 3558, 2920],
 [3983, 2154, 2193, 945, 362, 708, 2699],
 [231,
  55,
  1948,
  566,
  3474,
  3526,
  25,
  2402,
  1110,
  630,
  3601,
  548,
  457,
  3463,
  587,
  362],
 [3742, 1146, 2155, 1363, 1511, 637],
 [2155, 2435, 2081, 2430, 1446, 2430, 4720],
 [1385, 2841, 1185, 1816, 1740, 1032, 3066, 972],
 [4305, 3073, 524, 135, 2920, 4577, 4807, 4318, 4225, 1937, 467, 1455],
 [3601, 3632, 655, 3473, 4202, 4631, 2330, 1363, 2850],
 [1391, 1358, 3537, 2001, 3498, 2998, 1678, 725],
 [4642, 768, 3823, 1632, 352, 305, 4483, 2342, 4921, 345, 3829, 2432, 2920],
 [3356,
  773,
  3368,
  768,
  3823,
  4592,
  3533,
  4882,
  1003,
  4957,
  773,
  3445,
  4401,
  4949,
  3198,
  2920],
 [3632, 4116, 903, 4622, 3794, 3630, 3742, 2198],
 [4555, 2320, 4626, 1327, 1877, 547, 2846, 773, 2090, 2576],
 [110,
  3881,
  1318,
  644,
  4608,
  2654,
  3617,
  362,
  4753,
  1738,
  4333,
  1379,
  3881,
  362,
  3765,
  2920],
 [2755, 2621, 1056, 3248, 3192, 3404, 1725, 2654],
 [2686, 3921, 2899, 1191, 4943, 1391, 1008],
 [3742, 385, 800, 2550, 246, 3970],
 [3742, 4300, 1468, 866, 3845, 1391, 214, 4567, 835, 1632],
 [597, 1391, 2183, 1672, 4150, 3954],
 [1391, 3504, 4861, 4940, 4581, 3742, 1883, 3742, 2198, 4773, 1273],
 [2417, 4524, 3948, 4014, 1391, 3970, 4466],
 [4884, 494, 47, 3686, 143, 2201, 3351, 4121, 4940],
 [2451, 2245, 4713, 1872, 4329, 2840, 3981, 1533, 486],
 [1391, 2867, 830, 3321, 4427, 2850],
 [2865, 2001, 2954, 2160, 2324, 3601],
 [891, 3002, 3807, 3472, 4973, 4291, 169],
 [1714],
 [945, 4396, 4853, 2914, 2271, 3771, 2495, 3448, 1363],
 [2301, 2371, 3213, 2198, 1511, 512, 4645, 1583, 2866, 2920],
 [3632, 3887, 2472, 1883, 3479, 3494, 835, 2670],
 [3341,
  1686,
  2101,
  4649,
  2894,
  4137,
  2954,
  2270,
  2889,
  2925,
  3558,
  2026,
  924,
  3664,
  2920],
 [131, 3425, 905, 3424, 2444, 731, 1143, 905, 4003, 4343, 2768, 4069, 4011],
 [4300, 1668, 102, 1873, 3076],
 [227, 2245, 4483, 2518, 2634, 992, 2216, 2266, 2001, 2245, 2809, 3945],
 [72, 3018, 3948, 1632, 793, 4997, 3356, 3595, 2405, 4983, 1018],
 [3761, 1262, 1813, 2894, 377, 4009, 2426, 3883, 1466],
 [3675, 3742, 3277, 3822, 345, 1966, 2760, 3742, 2198, 2760, 4001, 1632],
 [2107, 2155, 4015, 4274, 1391, 3108],
 [1748, 954, 2005, 1724, 1391, 835, 954, 1991, 1289, 1909, 1212],
 [3594, 4081, 1632, 1124, 1391, 3445, 4922, 1439, 3474],
 [3032, 3455, 790, 1766, 1391, 440, 4309, 3113, 147, 3371, 2920],
 [1018, 4591, 1617, 2131, 1289, 1909, 4622, 418, 3313, 385, 1391],
 [3175, 261, 187, 777, 1766, 1273, 3156, 566, 2903, 1391],
 [3742, 3983, 4857, 3880, 25, 3887, 3970, 22],
 [222, 4011, 2078, 1260, 799, 4502, 4970, 2116, 3681, 3880],
 [3566, 2954, 1065, 1406, 3213, 1288, 1391, 1151, 659, 196, 2297, 2155, 3846],
 [3290, 2846, 4274, 1933, 901, 2547, 3845, 3146],
 [3983, 1845, 1391, 2899, 3226, 2508, 2456],
 [4642, 4226, 1406, 4274, 1391, 2430, 1096, 512, 1247, 987],
 [2686, 1191, 722, 1593, 2596, 3955, 1260, 2005],
 [902, 3614, 254, 572, 39, 3799, 4361, 397, 377],
 [3435, 3604, 4019, 2812, 3948, 2051, 4064, 3473],
 [2771, 3682, 1391, 180, 1440, 3333, 527],
 [3929, 1385, 2495, 1391, 1326, 3233, 3443, 2867, 3348, 2203, 3945],
 [2155, 4086, 2423, 959, 1, 4011, 1391, 2920],
 [1480, 2821, 605, 1391, 4075, 87, 2228],
 [1391, 1632, 1936, 4943, 2913, 3790, 3256],
 [2359, 2283, 2036, 726, 3546, 4120, 2124, 3695, 3742, 1379, 1399],
 [4844, 3870, 2266, 184, 57, 1632, 901, 3935],
 [1593, 77, 2154, 3002, 4809, 4137, 2001, 3247, 1497, 2199],
 [2641, 3259, 4187, 605, 1558, 4641, 4131, 2576],
 [1879, 1632, 68, 2472, 3948, 1320, 3880],
 [4014, 121, 3793, 2276, 4822, 1048, 1391],
 [2686, 1631, 1335, 1391, 3443, 3305, 3311, 1672, 2587],
 [1391, 3008, 2253, 4822, 972, 1706, 2430, 1599, 4101],
 [2816, 1589, 72, 1711, 3247, 1665, 3781],
 [1391, 3970, 441, 1455, 494, 571, 4510],
 [1391, 335, 507, 3760, 1777, 2705, 3445, 4913, 2920],
 [1388, 612, 1632, 3219, 3790, 2779, 2129, 1707],
 [4383, 1707, 1391, 3305, 1777, 1686, 2503, 3443],
 [4642, 2099, 319, 2800, 771, 3695, 1615, 4853, 4183, 1097],
 [3761, 4510, 1163, 4461, 3442, 2140, 1312, 1283, 972],
 [2228, 1998, 3849, 1149, 1416, 1018, 3369],
 [1933, 2654, 2400, 1889, 2561, 2633, 4829, 1406],
 [1933, 1705, 4236, 4300, 4672, 1380, 4841],
 [1560, 4611, 4148, 2826, 2879, 1391, 4261, 1758, 4952, 815, 2920],
 [1391, 115, 3192, 3549, 2188, 2330, 1363, 3983],
 [947, 2155, 1928, 1631, 4081, 1391, 1439, 2308, 823, 1952],
 [1892, 2621, 87, 1625, 901, 2621, 371, 4922, 2001, 1857, 2420],
 [1650, 3929, 4483, 1039, 1514, 2791, 903, 3887, 2518, 305, 2675, 2920],
 [3823, 1738, 4274, 3790, 3256, 1777, 4427, 1662, 2920],
 [1074, 427, 4200, 2210, 2155, 2386, 507, 337, 4397, 2210, 2920],
 [3488, 4856, 736, 1860, 1909, 4511, 4611, 879, 1444, 2920],
 [835, 1125, 1832, 2213, 4465, 1076, 2386, 184, 3007, 3102, 2920],
 [1391, 315, 3360, 3428, 2417, 433, 2670, 4011, 3601, 3632],
 [3894, 3987, 2090, 780, 2654, 4150, 512, 3936, 2920],
 [1391, 2738, 1672, 22, 2064, 1686, 4015],
 [2332, 4, 1391, 2389, 1044, 2771],
 [4897, 4606, 4098, 448, 264, 3265, 1379, 605, 3699, 3765],
 [4844, 512, 3443, 1391, 2253, 3348, 180, 3443],
 [891, 3002, 3742, 286, 1692, 2400, 1391, 2998],
 [4567, 1630, 2034, 1358, 3315, 4353, 358, 269, 1122],
 [1391, 2199, 2180, 4150, 1711, 797, 4298, 440, 2920],
 [4983, 1098, 1044, 3024, 560, 2090, 902, 1047],
 [587, 3324, 324, 4868, 2257, 303],
 [3742, 2216, 291, 2320, 432, 1978, 2791, 4013, 2245],
 [2920, 669, 4913, 2180, 2639, 3122, 2155, 1363, 4450, 4819],
 [40, 3699, 945, 1000, 1018, 4847],
 [3601, 3632, 1632, 2631, 1098, 1391, 1739],
 [2078, 4853, 4940, 2791, 3561, 1379, 747, 1879],
 [3129, 4081, 3488, 2577, 866, 2460, 3192, 777, 4928],
 [1406, 4897, 687, 4292, 2071, 2894, 2414, 721, 3213, 4961, 4685, 2920],
 [3617, 695, 2301, 1738, 3346, 2580, 488, 1391, 4302, 2920],
 [1632,
  2155,
  4592,
  4973,
  747,
  945,
  607,
  4560,
  3770,
  2081,
  242,
  1363,
  3213,
  1400,
  3377],
 [1910, 4853, 1928, 2155, 257, 3500, 2090, 7, 4277, 4013, 2090, 2920],
 [1933, 2576, 777, 1246, 708, 723, 787, 3245, 4013, 2245, 2966],
 [1672,
  1119,
  1097,
  4918,
  626,
  2180,
  4631,
  3213,
  77,
  3558,
  4428,
  4101,
  1761,
  4311],
 [1480, 4075, 3352, 897, 857, 4600, 87, 3305],
 [3445, 415, 1391, 4721, 280, 2480, 4633, 3686, 3201, 1122, 4043],
 [4276, 1686, 4300, 3742, 3807, 3472, 770],
 [719, 1525, 3630, 2609, 3660, 1436, 1434, 4644],
 [2180, 1306, 4466, 2163, 2699, 294, 47, 3686, 2920],
 [2859, 3018, 2886, 3605, 2399, 3820, 1429, 2771, 973],
 [622,
  154,
  2320,
  676,
  4013,
  4822,
  3887,
  1,
  2455,
  1396,
  1097,
  596,
  3523,
  4506,
  1379,
  1869,
  2706,
  280,
  2480,
  2920],
 [2248, 120, 1391, 3443, 1632, 867, 4665, 2793],
 [4642, 220, 1391, 3192, 4274, 2301, 183, 3269, 25, 1711],
 [1406, 1560, 4952, 1391, 3883, 4918, 3443],
 [787, 1919, 824, 2706, 377, 3728, 3637, 4700],
 [1879, 2201, 2155, 1832, 3682, 1196, 3813, 1229, 3059],
 [824, 4940, 1115, 1124, 4333, 4868, 4954],
 [72, 3608, 2706, 4377, 4015, 3820, 4731],
 [2263, 2632, 1937, 3040, 1416, 1335, 4819, 882, 1191, 1864, 2898, 3445],
 [945, 2755, 2654, 2815, 3219, 385, 1228, 3018],
 [2771, 2199, 606, 4519, 4606, 777, 4952, 1391],
 [2263,
  318,
  2670,
  1044,
  2654,
  1391,
  3849,
  4592,
  1670,
  2891,
  98,
  2090,
  4773,
  4729,
  1842,
  2920],
 [3504, 4050, 2954, 432, 3866, 220, 4720, 3024],
 [105, 2472, 1632, 2887, 1031, 3068, 4551],
 [1617, 2090, 1793, 4724, 4331, 1257, 3699],
 [4642, 3740, 4316, 4737, 1570, 4074, 2763, 2920],
 [3742, 2914, 2264, 3839, 1678, 4417, 901, 972],
 [1391, 3474, 385, 3922, 4564],
 [2945, 4631, 3506, 580, 1391],
 [178,
  4483,
  936,
  3943,
  646,
  3093,
  1929,
  2155,
  362,
  1264,
  2852,
  1388,
  4277,
  4013,
  2090,
  2001,
  2920],
 [3601, 3632, 1632, 3612, 69, 1289, 4949, 3525, 4095, 4680],
 [1191,
  1391,
  1086,
  3024,
  4834,
  3691,
  2998,
  3455,
  1379,
  4081,
  2954,
  3071,
  3973,
  3601,
  3632,
  4504,
  3351,
  1260,
  3053],
 [891, 2245, 3558, 1044, 675, 2473, 747, 4567],
 [4952, 1391, 3443, 169, 2675, 1131, 1879, 3192, 3443],
 [1941, 688, 361, 3201, 3951, 547, 2693],
 [3761, 4510, 949, 2765, 1401, 147, 1287, 2705, 790],
 [4585, 2253, 4952, 1391, 4897, 2004, 4844, 1632, 3614, 1511, 2920],
 [3881, 2036, 746, 2304, 4844, 2203, 2423],
 [3742, 167, 2456, 1632, 628, 587, 1461, 494, 891, 4210],
 [292, 2154, 68, 3603, 22, 63, 2954, 3558, 4191],
 [1416, 3699, 3259, 3002, 3407, 2131, 385, 1517, 3324],
 [3308, 68, 3887, 3121, 1738, 3699, 3404, 3742, 3632],
 [2771, 2199, 246, 571, 3632, 4300, 91],
 [4081, 2155, 3032, 2008, 4316, 1832, 4705, 2920],
 [3341,
  1686,
  1391,
  3707,
  3833,
  2417,
  3790,
  3256,
  3165,
  2417,
  3790,
  2779,
  2920],
 [3057, 4300, 903, 4983, 2577, 688],
 [2326, 1632, 4300, 685, 3104, 3742, 3506, 328, 1544],
 [4607, 1391, 3974, 2203, 4226, 4882, 1406, 2920],
 [3742, 2859, 121, 891, 4069, 824, 1883, 3807, 3472],
 [688, 1642, 2021, 2271, 3472, 269, 2090],
 [72, 3352, 4456, 605, 905, 4395, 3630, 3371, 3948, 1326],
 [3412, 1612, 2245, 1311, 1363, 4728, 162, 1363],
 [3983, 388, 2640, 3724, 3970, 2738, 2071],
 [4630, 2426, 1401, 4303, 2922, 4285, 998, 187],
 [72, 1632, 3351, 4064, 1115, 3595, 3362, 2090, 3614, 1863, 4305],
 [3285, 3514, 385, 2774, 4844, 2771, 385, 4427, 4868],
 [72, 793, 3657, 835, 184, 894],
 [1672, 1003, 2098, 1208, 3605, 3040, 2779, 2206],
 [3742, 3983, 3002, 1961, 4205, 2466, 2557, 2927, 966],
 [927, 4592, 4333, 1834, 4579, 4954],
 [3742, 4081, 1391, 4196, 3630, 2628, 1008],
 [1933, 1437, 2064, 2193, 4013, 2245, 1978, 3601, 3362],
 [4537, 2729, 3488, 2607, 355, 4291, 1183, 3823, 2920],
 [654, 593, 736, 1391, 3474, 1063, 3974, 3601, 3632, 88, 2920],
 [237, 1589, 2472, 4027, 4305, 4728, 237, 1124, 767],
 [2254, 3018, 1897, 3945, 1391, 1848, 4585, 1686],
 [2956, 1954, 3940, 4952, 1391, 2397, 4945, 1326, 773, 2920],
 [1777,
  1686,
  1406,
  977,
  4303,
  3213,
  4037,
  172,
  3424,
  2083,
  4509,
  1633,
  2574,
  3078,
  2920],
 [1391, 1101, 47, 3455, 3881, 1326, 3546, 2984],
 [4300, 1335, 3255, 2036, 2420, 4720, 1380, 3290],
 [4126,
  772,
  1122,
  1462,
  4591,
  3289,
  3691,
  2183,
  3834,
  430,
  303,
  1097,
  596,
  3616,
  3484],
 [439, 4843, 3255, 4952, 1391, 4212, 969, 2998],
 [3507, 2789, 2743, 4753, 780, 1919, 3697, 362],
 [3341,
  2920,
  516,
  4740,
  1110,
  2079,
  4162,
  1326,
  2094,
  2580,
  3794,
  2155,
  2953,
  799,
  2074,
  4740,
  2861,
  2670,
  1321,
  3313],
 [4642, 2084, 2446, 507, 1391, 2889, 1044, 2083],
 [1617, 3760, 2094, 4948, 3082, 4642, 3283, 132, 3029, 977, 3213, 3822, 4183],
 [3887, 385, 2171, 3742, 2198, 27, 1326, 3537, 4210],
 [3360, 3428, 1632, 3356, 1391, 1335, 4829, 2417, 1998, 4887],
 [1721, 87, 3920, 945, 2663, 1341, 3082, 1391, 3790, 3256],
 [4581, 1391, 2246, 2154, 685, 2001, 1777, 1686, 2889, 2920],
 [61, 2577, 1272, 3424, 1391, 1594, 3822],
 [3983, 3887, 2754, 4952, 1391, 41, 4291, 2263, 3822, 1246, 1813],
 [1879, 4160, 1577, 1936, 3029, 510, 4163, 4585, 4291, 1910, 1191],
 [572, 824, 2730, 1678, 2470, 2654],
 [4884, 1363, 352, 3983, 3699, 3765, 4918, 3461, 3868, 2694],
 [2154, 2815, 2738, 91, 346, 4300, 2815, 3851, 3742, 385],
 [1191, 3742, 3983, 1724, 3659, 4018, 3324],
 [4639, 3777, 193, 1112, 3071, 3961, 1809, 4913],
 [2530, 3731, 105, 1444, 311, 2778, 3315, 527],
 [3827, 1311, 977, 3742, 47, 1687, 1678, 1391, 4255, 4940],
 [3843, 2433, 2015, 3424, 1401, 3632, 1183, 45, 4333],
 [1391, 4897, 1427, 1461, 2953, 463, 1044, 945, 4396, 1273, 1066, 3443],
 [547, 3259, 1632, 167, 2405, 512, 4970],
 [1391, 1663, 2181, 4788, 1925, 945, 763, 2574, 1357, 961],
 [1391, 3774, 2738, 2097, 973, 3165, 2472],
 [4300, 1497, 4740, 3742, 3794, 1437, 4720, 770],
 [72, 3948, 115, 531, 147, 3447, 2036, 3627],
 [1391, 1, 1813, 3929, 4299, 773, 3445, 4776, 2503, 250],
 [2107, 2026, 1115, 1968, 3504, 22, 4081],
 [1191, 3742, 3983, 1632, 1273, 1260, 945, 3807, 3472, 2852],
 [2107, 3341, 3038, 1229, 687, 1632, 385, 1391],
 [1111, 3449, 465, 3830, 3406, 782, 4694, 902, 703, 2510, 2690, 1389],
 [72, 2472, 2815, 2508, 1760, 464, 3008],
 [3742, 3272, 2339, 3137, 4074, 927, 1391],
 [3008, 972, 3024, 1937, 3192, 2550, 4194, 3074],
 [547, 4713, 2129, 790, 1741, 4150, 2699, 945, 3742, 690],
 [3742, 804, 1028, 3036, 4185, 804, 2550, 3807, 701, 1254],
 [2686, 3921, 1612, 4943, 1391, 1008],
 [4899,
  4145,
  2086,
  4852,
  2354,
  4145,
  3459,
  2176,
  2316,
  4554,
  2086,
  4852,
  2354,
  2804,
  2145,
  3231,
  4473,
  2770,
  2354,
  1738,
  2021,
  2889,
  958,
  2316,
  3899,
  3265,
  3040],
 [2083, 2953, 4081, 1391, 3581, 2654, 2605, 3874, 4043, 3201],
 [4822, 1632, 2065, 1124, 1391, 3445],
 [2634, 1943, 3621, 4728, 4720, 1998, 3794, 3787, 3742, 2198],
 [2155,
  2343,
  2444,
  893,
  2417,
  4844,
  530,
  3742,
  2654,
  2982,
  4333,
  2682,
  1037,
  4427,
  3358,
  507,
  4899,
  4579,
  4844,
  2771,
  2963],
 [2036, 945, 162, 184, 527, 1937, 1059, 4899, 1191, 734, 2920],
 [2757, 3581, 739, 3985, 2005, 2821],
 [4300, 531, 147, 4000, 4720, 4555, 2668],
 [2853, 3201, 4210, 3474, 4821, 446, 3329, 3023],
 [1097, 1877, 1014, 4693, 362, 3230, 1272, 3640, 3864],
 [3983, 4274, 388, 2193, 22, 3324],
 [1391, 1596, 1086, 945, 3891, 2771, 3463, 1391, 4795],
 [122, 1391, 1363, 4973, 2405, 3983, 2818, 4557, 4302, 332],
 [4952, 1391, 4592, 4509, 3979, 2496, 4075, 1391, 4390, 4822],
 [4081, 2155, 4274, 1391, 977, 4300, 3324, 3699, 4623],
 [4150, 2699, 1406, 3601, 1617, 4863, 4322, 2180, 1937, 1044, 2920],
 [1391, 2400, 3201, 102, 1668, 3767, 2201],
 [3341,
  2343,
  1318,
  4853,
  415,
  4844,
  2266,
  1217,
  780,
  2738,
  1363,
  3333,
  4844,
  3605,
  2193],
 [3742, 1883, 3165, 4575, 4120, 2741, 3277, 3822, 4465],
 [1059, 1379, 1632, 2771, 3455, 184, 1391, 1440, 3333, 527],
 [375, 1396, 3887, 3111, 3551, 4820, 4753],
 [1391, 3560, 1122, 4233, 4987, 2193, 4045],
 [3735, 1618, 91, 4665, 1705, 3610, 68],
 [2276, 3669, 3742, 3341, 954, 4010, 4436],
 [2647, 162, 4868, 1592, 3834, 1391],
 [3488, 4856, 1963, 3301, 2065, 2276, 3880, 2920],
 [4185, 4930, 1632, 55, 1813, 841, 2952, 4150, 3424, 2654, 3558],
 [4299, 1948, 4614, 824, 3868, 3025, 3699, 1848],
 [3827, 1311, 949, 4395, 4776, 335, 4580],
 [314, 3742, 3341, 2094, 1839, 1327, 2253, 2090, 1328],
 [3018, 3948, 315, 1391, 2368, 1632, 2235, 3168, 2176],
 [3369,
  1937,
  4333,
  3506,
  3742,
  1014,
  385,
  1391,
  959,
  1857,
  4333,
  905,
  385,
  1260],
 [1912, 2962, 4274, 4438, 3699, 2196, 3955, 1260, 175],
 [25, 3887, 1632, 3893, 3289, 4922, 3699, 3222, 2914, 1206, 1363, 1084],
 [1714],
 [2049, 3098, 944, 344, 2430, 3710, 3887, 1132, 2352, 3945],
 [1391, 3894, 4922, 117, 3518, 824, 1690, 3277, 3822],
 [4294, 777, 102, 3055, 1497, 4058, 94, 2849, 1991, 3883, 2662],
 [2596, 1672, 3213, 768, 3594, 305, 812, 41, 1044, 4315, 2155, 3443],
 [835, 4675, 507, 4952, 1391, 3749, 104, 1777, 1686, 2920],
 [1391, 4631, 3356, 1361, 3361, 2196, 991, 2422],
 [1755, 3640, 4972, 2263, 2632, 3948, 3247, 4869, 2420, 1678, 68],
 [4081, 1391, 4644, 3436, 2670, 62],
 [41, 1391, 3192, 1738, 539, 1044, 2699, 4150, 2920],
 [864, 701, 1113, 679, 4075, 479, 4943, 1456, 3813, 22, 531, 147],
 [4681, 4506, 362, 2706, 4753, 2248, 790, 4518, 2449, 2920],
 [3400, 867, 1198, 1782, 644, 1287, 3351, 1097],
 [2155, 1632, 1391, 1672, 3822, 3118],
 [3601, 3632, 1632, 4951, 4897, 466, 3248, 2913, 3790, 2623],
 [314, 2046, 3085, 3038, 271, 2222],
 [4486, 3243, 2952, 2026, 2641, 3290, 2846, 1632],
 [891, 4465, 2997, 3560, 2887, 4721, 1612, 1024],
 [2871, 3341, 175, 2982, 2199, 3955, 3659, 3948, 3382],
 [2326, 4049, 1391, 2074, 1363, 1632, 2154, 3146, 4442],
 [903, 787, 922, 2472, 4274, 1044, 3192, 1677, 3301],
 [3742, 3983, 934, 688, 4300, 3749],
 [1677, 1853, 121, 1686, 3301, 2228, 1098],
 [261, 2245, 1336, 389, 2954, 2005, 4829],
 [1910, 2686, 3834, 305, 4628, 2888, 1797, 3009],
 [2645, 2433, 3954, 4922, 3523, 3760, 2036, 2216, 2356, 2473],
 [1391, 1632, 4210, 945, 4940, 4417, 901, 4579, 1379],
 [2920, 4150, 1617, 676, 1406, 777, 725, 582, 1734],
 [1919, 4739, 4330, 2339, 3894, 3480],
 [4333, 3883, 3881, 1883, 1391, 4044, 3442, 3289, 1748, 1582, 3883, 2920],
 [3301, 2934, 3265, 2868, 1853, 448],
 [2326, 1632, 3213, 4847, 1391, 3683, 3255],
 [72, 1455, 3425, 2046, 172, 3055, 601, 1852],

In [42]:
corpus[1]

'china say trump call taiwan presid chang island statu'

In [43]:
onehot_repr[1]

[891, 1632, 1391, 4274, 1692, 4081, 2631, 4187, 2235]

### Embedding Representation

In [44]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1856 1146 1633 ...    0    0    0]
 [ 891 1632 1391 ...    0    0    0]
 [2503 1391 1877 ...    0    0    0]
 ...
 [1391 3341 1133 ...    0    0    0]
 [2539 1499 2495 ...    0    0    0]
 [ 851 3661  777 ...    0    0    0]]

In [45]:
embedded_docs[1]

array([ 891, 1632, 1391, 4274, 1692, 4081, 2631, 4187, 2235,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [46]:
embedded_docs[0]

array([1856, 1146, 1633, 2574, 3894, 1287, 1391,  725,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [62]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_shape=(sent_length,)))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None

In [63]:
len(embedded_docs),y.shape

(24353, (24353,))

In [64]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [65]:
X_final.shape,y_final.shape

((24353, 20), (24353,))

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.2, random_state=42)

### Model Training

In [92]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9720 - loss: 0.0718 - val_accuracy: 0.9045 - val_loss: 0.4035
Epoch 2/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9769 - loss: 0.0611 - val_accuracy: 0.9031 - val_loss: 0.4174
Epoch 3/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9773 - loss: 0.0581 - val_accuracy: 0.8984 - val_loss: 0.3770
Epoch 4/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9807 - loss: 0.0503 - val_accuracy: 0.9006 - val_loss: 0.4041
Epoch 5/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9828 - loss: 0.0465 - val_accuracy: 0.9013 - val_loss: 0.4198
Epoch 6/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9836 - loss: 0.0437 - val_accuracy: 0.9008 - val_loss: 0.4832
Epoch 7/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9848 - loss: 0.0393 - val_accuracy: 0.8986 - val_loss: 0.4674
Epoch 8/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9873 - loss: 0.0341 - val_accuracy: 0.9023 - val_loss: 0.4584
Epoch 9/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9875 - loss: 0.0330 - val_accuracy: 0.8986 - val_loss: 0.4281
Epoch 10/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9883 - loss: 0.0297 - val_accuracy: 0.8959 - val_loss: 0.5668
Epoch 11/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9878 - loss: 0.0312 - val_accuracy: 0.9019 - val_loss: 0.5192
Epoch 12/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9891 - loss: 0.0271 - val_accuracy: 0.8980 - val_loss: 0.4822
Epoch 13/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9884 - loss: 0.0291 - val_accuracy: 0.8969 - val_loss: 0.5870
Epoch 14/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9898 - loss: 0.0238 - val_accuracy: 0.8955 - val_loss: 0.5773
Epoch 15/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9924 - loss: 0.0200 - val_accuracy: 0.9013 - val_loss: 0.5845
Epoch 16/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9918 - loss: 0.0204 - val_accuracy: 0.8971 - val_loss: 0.5827
Epoch 17/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9921 - loss: 0.0204 - val_accuracy: 0.8984 - val_loss: 0.5291
Epoch 18/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9932 - loss: 0.0191 - val_accuracy: 0.8988 - val_loss: 0.5565
Epoch 19/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9922 - loss: 0.0170 - val_accuracy: 0.8976 - val_loss: 0.6880
Epoch 20/20
305/305 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9920 - loss: 0.0188 - val_accuracy: 0.9015 - val_loss: 0.6072

### Adding Dropout

In [ ]:
# from tensorflow.keras.layers import Dropout
# ## Creating model
# embedding_vector_features=40
# model=Sequential()
# model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model.add(Dropout(0.3))
# model.add(LSTM(100))
# model.add(Dropout(0.3))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [93]:
y_pred=model.predict(X_test)

153/153 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [94]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [95]:
from sklearn.metrics import confusion_matrix

In [96]:
confusion_matrix(y_test,y_pred)

array([[1966,  249],
       [ 231, 2425]])

In [97]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9014576062410182

In [98]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89      2215
           1       0.91      0.91      0.91      2656

    accuracy                           0.90      4871
   macro avg       0.90      0.90      0.90      4871
weighted avg       0.90      0.90      0.90      4871

In [60]:
0